### ISSUE TITLE
Suggested edit re: "reverse isms"

### ISSUE THREAD

**Issue by leahvelleman** [lgbtq-technology/coc-rewrite-2021#2]
> No “Reverse”-isms, including “reverse racism,” “reverse sexism,” and “cisphobia” or debating the rights and lived experiences of marginalized people in the community.

This is ambiguous — it could be taken to mean either "don't engage in reverse racism [which we think is a real thing]" or "don't accuse people of reverse racism [since we know it's not a real thing]." Given the norms of the community, I'm sure I know which one you mean, but it would be better to clarify explicitly for people who don't know those norms.

**Comment by tsaomao** [comment]
Discussed and refactored with 4 of 9 admins. Changing text by breaking out into two lines:

> No use or abuse of "Reverse"-isms, including "reverse racism," "reverse sexism," and "cisphobia" against marginalized members. "Reverse"-isms and any concept that uphold and bulwhark white and privileged supremacies out of the context of challenging it will be shut down.

and 

> No debating the rights and lived experiences of marginalized people in the community. 

Thanks for your feedback!
